name: CI

on:
  push:
    branches: [ master, ci ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DEVKITPRO: /opt/devkitpro
      DEVKITPPC: /opt/devkitpro/devkitPPC
      DEVKITARM: /opt/devkitpro/devkitARM
      WUT_ROOT: /opt/devkitpro/wut

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Pacman
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "devkitPro/pacman"
          version: "latest"
          file: "devkitpro-pacman.amd64.deb"
          
      - name: Install dependencies
        run: |
            sudo dpkg -i devkitpro-pacman.amd64.deb
            sudo dkp-pacman -Syuu wiiu-dev wut wiiu-tools --noconfirm --needed
               
          
